spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectms
    username: postgres
    password: Santosh@1497
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080